# Generated by Django 3.2 on 2022-01-27 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('check_in_sender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_path', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Traveller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='aircompany',
            options={'verbose_name': 'Aircompany', 'verbose_name_plural': 'Aircompanies'},
        ),
        migrations.AlterField(
            model_name='aircompany',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='EmailTraveller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check_in_sender.email')),
                ('traveller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check_in_sender.traveller')),
            ],
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='check-in date')),
                ('status', models.CharField(max_length=10)),
                ('aircompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check_in_sender.aircompany')),
                ('traveller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check_in_sender.traveller')),
            ],
        ),
    ]
